### ISSUE TITLE
"Index was outside the bounds of the array" exception when trying to display Legend on CartazianChart

### ISSUE THREAD

**Issue by drormekorot** [beto-rodriguez/LiveCharts2#1054]
XamarinForms 2.0.0 beta 710.

I have a view that loads the data from the server when `OnAppearing` runs.
The data is usually measurements over time.
So I used the following config to display the chart:

`<lvc:CartesianChart`
`      HorizontalOptions="Fill"`
`      Series="{Binding Series}"`
`      VerticalOptions="Fill"`
`      XAxes="{Binding XAxes}"`
`      YAxes="{Binding YAxes}"`
`      ZoomMode="Both" />`

and the ViewModel:

`public ObservableCollection<ISeries> Series { get; set; }`
`public ObservableCollection<ICartesianAxis> XAxes { get; set; }`
`public ObservableCollection<ICartesianAxis> YAxes { get; set; }`

Then when the data arrives I clear `Series`, `XAxes` and `YAxes`, and according to the data I re-add the axes (there might be discrete values instead of measurements so I don't know how the axes should be displayed beforehand) and the series.

The issue is, sometimes there is more than one series, so I need a legend to be displayed.

When I add `LegendPosition="Top"`, An exception is thrown.

Stack trace:
`Index was outside the bounds of the array`
  	`0x1E in LiveChartsCore.VisualElements.VisualElement<LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext>.Invalidate`
` 	0x2 in LiveChartsCore.Chart<LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext>.AddVisual	`
` 	0x1F1 in LiveChartsCore.SkiaSharpView.SKCharts.SKDefaultLegend.LiveChartsCore.Kernel.Sketches.IChartLegend<LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext>.Draw	`
` 	0xEE in LiveChartsCore.Chart<LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext>.DrawLegend`
` 	0x633 in LiveChartsCore.CartesianChart<LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext>.Measure`
` 	0x17 in LiveChartsCore.Chart<LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext>.<UpdateThrottlerUnlocked>b__144_1	`

Happens on both Android and iOS

**Comment by drormekorot** [comment]
Found a workaround.

After the axes and series are instantiated:
`PlotView.Legend = new SKDefaultLegend();`
`PlotView.LegendPosition = LiveChartsCore.Measure.LegendPosition.Top;`

**Comment by VMelnalksnis** [comment]
I'm having a similiar issue with `LiveChartsCore.SkiaSharpView.Avalonia 2.0.0-beta.800`.
Here's the view:
```charp
<liveChartsCore:CartesianChart
    Series="{Binding Series}" XAxes="{Binding XAxes}"
    ZoomMode="X" TooltipPosition="Hidden" />
```
where `Series` is `List<CandlesticksSeries<FinancialPoint>>` and `XAxes` is `List<ICartesianAxis>`. Both lists are initialized as empty, and the exception is thrown on view creation before adding data to series/axes.

Here's the stacktrace:
```csharp
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at LiveChartsCore.VisualElements.VisualElement`1.Invalidate(Chart`1 chart)
   at LiveChartsCore.Chart`1.AddVisual(ChartElement`1 element)
   at LiveChartsCore.SkiaSharpView.SKCharts.SKDefaultLegend.Draw(Chart`1 chart)
   at LiveChartsCore.Chart`1.DrawLegend(Single& ts, Single& bs, Single& ls, Single& rs)
   at LiveChartsCore.CartesianChart`1.Measure()
   at LiveChartsCore.Chart`1.<UpdateThrottlerUnlocked>b__142_1()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 181
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 263
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
```

**Comment by VMelnalksnis** [comment]
What helped in my case was adding `YAxes` and initializing it to `new() { new Axis() }`. What's weird is that this does not happen with `StackedColumnSeries<DateTimePoint>`, so I'm guessing this is not the intended behavior.

**Comment by ambertape** [comment]
I get the same with Avalonia 
`System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at LiveChartsCore.CartesianChart`1.Measure()
   at LiveChartsCore.Chart`1.<UpdateThrottlerUnlocked>b__142_1()
   at Avalonia.Threading.DispatcherOperation.InvokeCore() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 274
   at Avalonia.Threading.DispatcherOperation.Execute() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 262
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job) in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 122
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 153
   at Avalonia.Threading.Dispatcher.Signaled() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 133
   at Avalonia.Native.DispatcherImpl.Events.Signaled() in /_/src/Avalonia.Native/DispatcherImpl.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnPlatformThreadingInterfaceEventsVTable.Signaled(Void* this) in /_/src/Avalonia.Native/Interop.Generated.cs:line 5220`

Previous solution with adding YAxes doesn't help.

**Comment by ambertape** [comment]
Yes, I'm sorry. I used a single object instead of array for binding.
Binding with Axis[] works properly and not throws exceptions
