### ISSUE TITLE
Crash while displaying constantly updating Chart for Hours

### ISSUE THREAD

**Issue by PhilippElhaus** [beto-rodriguez/LiveCharts2#124]
I had **LiveCharts WPF (V2 beta 16)** running for 2-3 hours on a machine nearby. Then it crashed out of the blue (had this happen a second time already). This seems to be a rare bug stemming from the LiveCharts lib and likely not my code as i have `try/catch` almost everywhere, `ToArray` converters at every `foreach `loop (the error suggests it's `foreach `related) and the error thrown was application wide without a possibility to catch. Boiling this info down, the conclusion i come to is to report this as a bug here:

Monday, August 2, 2021 1:10 AM: Unknown Application Wide Exception: 
Collection was modified; enumeration operation may not execute.
    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
    at LiveChartsCore.Kernel.Data.DataProvider`2.Fetch(ISeries`1 series, IChart chart)+MoveNext()
    at LiveChartsCore.Kernel.Data.DataProvider`2.GetCartesianBounds(CartesianChart`1 chart, IChartSeries`1 series, IAxis`1 x, IAxis`1 y)
    at LiveChartsCore.CartesianSeries`4.GetBounds(CartesianChart`1 chart, IAxis`1 x, IAxis`1 y)
    at LiveChartsCore.LineSeries`9.GetBounds(CartesianChart`1 chart, IAxis`1 secondaryAxis, IAxis`1 primaryAxis)
    at LiveChartsCore.CartesianChart`1.Measure()
    at LiveChartsCore.Kernel.ActionThrottler.Call()
    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by beto-rodriguez** [comment]
This could be a threading issue.

I just reviewed and added a sample to debug this scenario.

I hope with the next release this issue is gone.

**Comment by beto-rodriguez** [comment]
Closing this, moved to #183
