### ISSUE TITLE
InvalidOperationException on points hover

### ISSUE THREAD

**Issue by rovany706** [beto-rodriguez/LiveCharts2#1264]
**Describe the bug**
Got an `InvalidOperationException` when hovering on points on line chart that is updated with a new point every second (not high frequency update).
It happens rarely, so I'm not sure how to reproduce it.

Stack trace:

```
Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at LiveChartsCore.Kernel.Providers.DataFactory`2.EnumerateIndexedEntities(ISeries`1 series, IChart chart)+MoveNext()
   at LiveChartsCore.Kernel.Providers.DataFactory`2.Fetch(ISeries`1 series, IChart chart)+MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at LiveChartsCore.Kernel.Extensions.SelectFirst[T,T1](IEnumerable`1 source, Func`2 predicate)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at LiveChartsCore.Kernel.Extensions._getCartesianTooltipLocation[TDrawingContext](IEnumerable`1 foundPoints, Chart`1 chart, LvcSize tooltipSize)
   at LiveChartsCore.Kernel.Extensions.GetTooltipLocation[TDrawingContext](IEnumerable`1 foundPoints, LvcSize tooltipSize, Chart`1 chart)
   at LiveChartsCore.SkiaSharpView.SKCharts.SKDefaultTooltip.Show(IEnumerable`1 foundPoints, Chart`1 chart)
   at LiveChartsCore.Chart`1.DrawToolTip()
   at LiveChartsCore.Chart`1.<TooltipThrottlerUnlocked>b__136_1()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at D2Oracle.Program.Main(String[] args) in /home/runner/work/d2-oracle/d2-oracle/src/D2Oracle/D2Oracle/Program.cs:line 15
```

**Libraries:**
 - LiveChartsCore.SkiaSharpView.Avalonia 2.0.0-rc1
 - Avalonia 11.0.4

**Desktop:**
 - Fedora 38

**Additional information:**
 - ViewModel that hosts and updates graph values is here: [link](https://github.com/rovany706/d2-oracle/blob/master/src/D2Oracle/D2Oracle/ViewModels/Dashboard/HeroDiagramsCardViewModel.cs)
 - View: [link](https://github.com/rovany706/d2-oracle/blob/master/src/D2Oracle/D2Oracle/Views/Dashboard/HeroDiagramsCardView.axaml)

**Comment by beto-rodriguez** [comment]
Hello

You normally get this error when the update comes from a different thread (not the UI)

See https://livecharts.dev/docs/Avalonia/2.0.0-rc1/samples.general.multiThreading for more info.

**Comment by rovany706** [comment]
Thanks a lot!
