### ISSUE TITLE
InvalidOperationException Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by Discostoff** [beto-rodriguez/LiveCharts2#1288]
When i try to write more than one lineseries in a CartesianChart, i get an System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

I tried with beta and latest prerelease version, same behavior.

```
[16:13:10 FTL] Exception: TaskScheduler:	System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Collection was modified; enumeration operation may not execute.)
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at LiveChartsCore.Kernel.Providers.DataFactory`2.EnumerateChartEntities(ISeries`1 series, IChart chart)+MoveNext()
   at LiveChartsCore.Kernel.Providers.DataFactory`2.Fetch(ISeries`1 series, IChart chart)+MoveNext()
   at LiveChartsCore.Kernel.Providers.DataFactory`2.GetCartesianBounds(Chart`1 chart, IChartSeries`1 series, IPlane plane1, IPlane plane2)
   at LiveChartsCore.CartesianSeries`4.GetBounds(CartesianChart`1 chart, ICartesianAxis secondaryAxis, ICartesianAxis primaryAxis)
   at LiveChartsCore.CartesianChart`1.Measure()
   at LiveChartsCore.Chart`1.<UpdateThrottlerUnlocked>b__142_1()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---

[16:13:10 FTL] Inner Exception: TaskScheduler:	System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at LiveChartsCore.Kernel.Providers.DataFactory`2.EnumerateChartEntities(ISeries`1 series, IChart chart)+MoveNext()
   at LiveChartsCore.Kernel.Providers.DataFactory`2.Fetch(ISeries`1 series, IChart chart)+MoveNext()
   at LiveChartsCore.Kernel.Providers.DataFactory`2.GetCartesianBounds(Chart`1 chart, IChartSeries`1 series, IPlane plane1, IPlane plane2)
   at LiveChartsCore.CartesianSeries`4.GetBounds(CartesianChart`1 chart, ICartesianAxis secondaryAxis, ICartesianAxis primaryAxis)
   at LiveChartsCore.CartesianChart`1.Measure()
   at LiveChartsCore.Chart`1.<UpdateThrottlerUnlocked>b__142_1()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at LiveChartsCore.Kernel.Providers.DataFactory`2.EnumerateChartEntities(ISeries`1 series, IChart chart)+MoveNext()
   at LiveChartsCore.Kernel.Providers.DataFactory`2.Fetch(ISeries`1 series, IChart chart)+MoveNext()
   at LiveChartsCore.Kernel.Providers.DataFactory`2.GetCartesianBounds(Chart`1 chart, IChartSeries`1 series, IPlane plane1, IPlane plane2)
   at LiveChartsCore.CartesianSeries`4.GetBounds(CartesianChart`1 chart, ICartesianAxis secondaryAxis, ICartesianAxis primaryAxis)
   at LiveChartsCore.CartesianChart`1.Measure()
   at LiveChartsCore.Chart`1.<UpdateThrottlerUnlocked>b__142_1()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[16:13:10 FTL] Unhandled exception: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Collection was modified; enumeration operation may not execute.)
```

```
public sealed class Input : Overlay<InputWindow>
{
    public ObservableCollection<ISeries> InputGraph { get; } = new();

    public LiveChartsCore.Measure.Margin Margin { get; set; } = new(-15);

    public Axis[] XAxes { get; set; }
            = new Axis[]
            {
                new Axis
                {
                    IsVisible = false,
                }
            };

    public Axis[] YAxes { get; set; }
            = new Axis[]
            {
                new Axis
                {
                    IsVisible = false,
                }
            };

    private ObservableCollection<ObservableValue> _speed = new();
    private ObservableCollection<ObservableValue> _bestSpeed = new();
    private ObservableCollection<ObservableValue> _throttle = new();
    private ObservableCollection<ObservableValue> _brake = new();
    private ObservableCollection<ObservableValue> _steerAngle = new();
    private ObservableCollection<ObservableValue> _minValue = new();
    private ObservableCollection<ObservableValue> _maxValue = new();

    private readonly LineSeries<ObservableValue> _speedLineSeries;
    private readonly LineSeries<ObservableValue> _bestSpeedLineSeries;
    private readonly LineSeries<ObservableValue> _throttleLineSeries;
    private readonly LineSeries<ObservableValue> _brakeLineSeries;
    private readonly LineSeries<ObservableValue> _steerAngleLineSeries;
    private readonly LineSeries<ObservableValue> _minValueLineSeries;
    private readonly LineSeries<ObservableValue> _maxValueLineSeries;

    private readonly InputConfig _config;
    private readonly ServiceAdapter _services;
    private Dictionary<int, float> _currentSessionBestLapSpeeds = new();

    public bool SteerAngle => _config.SteerAngle;
    public bool Speed => _config.Speed;

    public Input(IOverlayConfig config, OverlayGlobalConfig globalConfig, ServiceAdapter service, IGearSpeedAssist<int> gearSpeedAssist, GamePadManager gamePadManager) : base(config, globalConfig, service, gamePadManager)
    {
        _config = (InputConfig)config;
        _services = service;

        _throttleLineSeries = new LineSeries<ObservableValue> {
            Values = _throttle,
            Fill = null,
            Stroke = new SolidColorPaint(SKColors.Yellow, 4),
            GeometrySize = 0,
            LineSmoothness = 0,
        };

        _brakeLineSeries = new LineSeries<ObservableValue> {
            Values = _brake,
            Fill = null,
            Stroke = new SolidColorPaint(SKColors.Red, 4),
            GeometrySize = 0,
            LineSmoothness = 0
        };

        _steerAngleLineSeries = new LineSeries<ObservableValue> {
            Values = _steerAngle,
            Fill = null,
            IsVisible = _config.SteerAngle,
            Stroke = new SolidColorPaint(SKColors.Gray, 3),
            GeometrySize = 0,
            LineSmoothness = 0
        };

        _speedLineSeries = new LineSeries<ObservableValue> {
            Values = _speed,
            Fill = null,
            IsVisible = _config.Speed,
            Stroke = new SolidColorPaint(SKColors.SkyBlue, 3),
            GeometrySize = 0,
            LineSmoothness = 0
        };

        _minValueLineSeries = new LineSeries<ObservableValue> {
            Values = _minValue,
            Fill = null,
            Stroke = new SolidColorPaint(SKColors.Gray, 0),
            ZIndex = 0,
            GeometrySize = 0,
            LineSmoothness = 0
        };

        _maxValueLineSeries = new LineSeries<ObservableValue> {
            Values = _maxValue,
            Fill = null,
            Stroke = new SolidColorPaint(SKColors.Gray, 0),
            ZIndex = 0,
            GeometrySize = 0,
            LineSmoothness = 0
        };

        var bestSpeedVisible = false;

        _bestSpeedLineSeries = new LineSeries<ObservableValue> {
            Values = _bestSpeed,
            Fill = null,
            IsVisible = bestSpeedVisible,
            Stroke = new SolidColorPaint(SKColors.Orange, 2),
            GeometrySize = 0,
            LineSmoothness = 0
        };

        InputGraph.Add(_throttleLineSeries);
        InputGraph.Add(_brakeLineSeries);
        InputGraph.Add(_steerAngleLineSeries);
        InputGraph.Add(_speedLineSeries);
        InputGraph.Add(_minValueLineSeries);
        InputGraph.Add(_maxValueLineSeries);
        InputGraph.Add(_bestSpeedLineSeries);

        _services.AccDataSourceService.TelemetryAccData += TelemetryAccData;
        _services.LapTimeService.New += LapTimeService_New;
    }

private void TelemetryAccData(AccData e)
{
    if (e is null || e.IsDefault || !_config.IsEnabled)
    {
        return;
    }

    var throttle = e.Physics.Gas;
    var brake = e.Physics.Brake;
    var steerAngle = (e.Physics.SteerAngle + 1f) * .5f;

    var maxValue = 150;

    var speed = e.Physics.SpeedKmh;

    var speedValue = speed / 300f;

    var sector = (int)(e.Graphics.normalizedCarPosition * 1000f);

    try
    {
        while (_throttle.Count >= maxValue)
        {
            _speed.RemoveAt(0);
            _throttle.RemoveAt(0);
            _brake.RemoveAt(0);
            _steerAngle.RemoveAt(0);
            _minValue.RemoveAt(0);
            _maxValue.RemoveAt(0);
        }

        while (_bestSpeed.Count >= maxValue)
        {
            _bestSpeed.RemoveAt(0);
        }

        _speed.Add(new ObservableValue(speedValue));
        _throttle.Add(new ObservableValue(throttle));
        _brake.Add(new ObservableValue(brake));
        _steerAngle.Add(new ObservableValue(steerAngle));
        _minValue.Add(new ObservableValue(0f));
        _maxValue.Add(new ObservableValue(1f));


        if (_currentSessionBestLapSpeeds.Count == 0) return;

        if (!_currentSessionBestLapSpeeds.TryGetValue(sector, out var value)) return;

        var speedsValue = value / 300f;

        _bestSpeed.Add(new ObservableValue(speedsValue));
    }
    catch (TaskCanceledException) { }
    catch (InvalidOperationException) { }
    catch (ArgumentOutOfRangeException) { }
    catch (IndexOutOfRangeException) { }
}
```

**Comment by beto-rodriguez** [comment]
Hello, my guess is that the `TelemetryAccData` and `TelemetryAccData` callbacks are not running on the UI tread, in this case you must invoke the changes on the UI thread or use a lock to sync your changes:

https://livecharts.dev/docs/Maui/2.0.0-rc1/samples.general.multiThreading

**Comment by beto-rodriguez** [comment]
I will close this for now, it seems that the issue in not on the LiveCharts side.

**Comment by Discostoff** [comment]
Normally the app crashs and shows me another error message when i have a threading problem. I would not think about that in first place. As i sad the problem only occurs if i have more than one line in the chart. But i can try to change my code. I did not see your first replay went straight into spam folder :D
