### ISSUE TITLE
Crash: Could not create a new view because the main window has not yet been created

### ISSUE THREAD

**Issue by jpageacsys** [beto-rodriguez/LiveCharts2#1354]
**Describe the bug**
After updating the library to RC2 the app crashes on any page with a chart. 

Here's the error:
```
WinRT information: Could not create a new view because the main window has not yet been created
'AcSYS Tools UWP.exe' (Win32): Loaded 'C:\Users\Joel\source\repos\AcSYS-Tools-WASDK\AcSYS Tools UWP\bin\x64\Debug\net7.0-windows10.0.22621\win10-x64\AppX\Microsoft.DiaSymReader.Native.amd64.dll'. 
'AcSYS Tools UWP.exe' (Win32): Loaded 'C:\Users\Joel\source\repos\AcSYS-Tools-WASDK\AcSYS Tools UWP\bin\x64\Debug\net7.0-windows10.0.22621\win10-x64\AppX\System.Reflection.Metadata.dll'. 
'AcSYS Tools UWP.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Joel\source\repos\AcSYS-Tools-WASDK\AcSYS Tools UWP\bin\x64\Debug\net7.0-windows10.0.22621\win10-x64\AppX\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'AcSYS Tools UWP.exe' (Win32): Loaded 'C:\Users\Joel\source\repos\AcSYS-Tools-WASDK\AcSYS Tools UWP\bin\x64\Debug\net7.0-windows10.0.22621\win10-x64\AppX\System.Collections.Immutable.dll'. 
'AcSYS Tools UWP.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Joel\source\repos\AcSYS-Tools-WASDK\AcSYS Tools UWP\bin\x64\Debug\net7.0-windows10.0.22621\win10-x64\AppX\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
System.InvalidOperationException: A method was called at an unexpected time.

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.ICoreImmersiveApplicationMethods.get_MainView(IObjectReference _obj)
   at Windows.ApplicationModel.Core.CoreApplication.get_MainView()
   at AcSYS_Tools_UWP.App.UnhandledError(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
```

**To Reproduce**
1. Create a WinUI 3 app with any chart.
2. Run the program

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22631.2506

**Comment by beto-rodriguez** [comment]
Sorry about that 😞, just pushed the rc2.1 version for WinUI, thanks for the report!

**Comment by jpageacsys** [comment]
Works great! Thank you for the quick fix 🙏
