### ISSUE TITLE
Description of the installation for Blazor WASM may not be sufficient. Got "System.DllNotFoundException: libSkiaSharp"

### ISSUE THREAD

**Issue by CReizner** [beto-rodriguez/LiveCharts2#1689]
**Describe the bug**
I tried the example in the installation description for Blazor WASM and get this error:
```
System.DllNotFoundException: libSkiaSharp [blazor.webassembly.js:1:46958]
at SkiaSharp.SKTypeface..cctor() [blazor.webassembly.js:1:46958]
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: ReferenceError: GL is not defined
Microsoft.JSInterop.JSException: ReferenceError: GL is not defined
 ---> ReferenceError: GL is not defined
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeJS(String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSInProcessRuntime.Invoke[GLInfo](String identifier, Int64 targetInstanceId, Object[] args)
   at Microsoft.JSInterop.Implementation.JSInProcessObjectReference.Invoke[GLInfo](String identifier, Object[] args)
   at SkiaSharp.Views.Blazor.Internal.JSModuleInterop.Invoke[GLInfo](String identifier, Object[] args)
   at SkiaSharp.Views.Blazor.Internal.SKHtmlCanvasInterop.InitGL()
   at SkiaSharp.Views.Blazor.SKGLView.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
This was a Blazor standalone project with NET 8. A similar error occurred with a Blazor app with InteractiveWebAssembly.
```
Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN7SRCQ37NGL", Request id "0HN7SRCQ37NGL:00000001": An unhandled exception was thrown by the application.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at SkiaSharp.Views.Blazor.SKGLView.Dispose()
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.DisposeAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<InvokeAsync>g__Execute|8_0(ValueTuple`3 state)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DisposeAsync()
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.<DisposeAsync>g__Await|26_0(Int32 i, ValueTask vt, List`1 toDispose)
         at Microsoft.AspNetCore.Http.Features.RequestServicesFeature.<DisposeAsync>g__Awaited|9_0(RequestServicesFeature servicesFeature, ValueTask vt)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<FireOnCompleted>g__ProcessEvents|242_0(HttpProtocol protocol, Stack`1 events)
```
I also tried adding the NuGet package SkiaSharp.NativeAssets.Linux. Then the Bilbiotek libSkiaSharp appears in the project, but the same error occurs.

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Browser Firefox; Chrome latest

**Comment by beto-rodriguez** [comment]
This is more likely an issue on SkiaSharp, I am not completely sure about the setup on Linux. Maybe you can find help on the SkiaSharp repo.

**Comment by corradolab** [comment]
Same issue here, Blazor 8 WASM running on Windows.

![Image](https://github.com/user-attachments/assets/396212d6-4a4d-4d55-babf-750b50cafed6)

Tried "X64" as target instead of "Any Cpu".
Also tried adding these in proj, grabbed from LiveCharts2 samples

`  <ItemGroup Condition="('$(UsingMicrosoftNETSdkBlazorWebAssembly)' == 'true' or '$(UsingMicrosoftNETSdkWebAssembly)' == 'true') and '$(TargetFrameworkVersion)' != ''">
    <NativeFileReference Include="$(MSBuildThisFileDirectory)..\output\native\wasm\libSkiaSharp.a\3.1.34\$(_SkiaSharpNativeBinaryType)\*.a" Condition="$([MSBuild]::VersionEquals($(TargetFrameworkVersion), '8.0'))" />
    <NativeFileReference Include="$(MSBuildThisFileDirectory)..\output\native\wasm\libSkiaSharp.a\3.1.56\$(_SkiaSharpNativeBinaryType)\*.a" Condition="$([MSBuild]::VersionGreaterThanOrEquals($(TargetFrameworkVersion), '9.0'))" />
  </ItemGroup>`

But error still there.

**Comment by squareboyy** [comment]
@CReizner hi, I encountered the same problem, did you manage to solve it?

**Comment by SanderVanGennip** [comment]
Trying to build / start the blazor samples for Live Charts 2 and running to the exact same problem. Anyone have a cause or solution yet?

**Comment by beto-rodriguez** [comment]
@SanderVanGennip did you tried the dev branch? 

<img width="849" height="53" alt="Image" src="https://github.com/user-attachments/assets/fe98a506-69ec-49ed-afb5-c4e0a802a32a" />

Normally this issue is fixed by updating SkiaSharp.

**Comment by SanderVanGennip** [comment]
@beto-rodriguez 

I initially tried the master branch. But after your suggestion I also tried the dev branch. It gave slightly different errors, but the core problem seemed to be the same: it is unable to load libskiasharp.

After hours of randomly trying stuff I found a way to get things working. This is based on the master branch, but I suspect that the fix for dev is very similar.

What I have done:

I have updated skia packages. (Probably not required)

I have added this to the BlazorSample.csproj:

```
<PropertyGroup>
    <WasmBuildNative>true</WasmBuildNative>
  </PropertyGroup>
```

After adding this, Visual Studio immediately tells me that I need to install wasm-tools-net8:

`dotnet install workload wasm-tools-net8`

After having done this and trying to build, you get that exact same error. And here was the thing that had me stumped: after closing Visual Studio and re-opening the project, all of a sudden everything worked!!

This cost me way more time than I feel comfortable with, but at least there is a result.

Hope this is helpful to you or others running into the same thing.

Best regards,

Sander

**Comment by quellwerk** [comment]
> dotnet install workload wasm-tools-net8

This solved it for me, too

**Comment by taublast** [comment]
As of today 

```bash
dotnet workload install wasm-tools
```

And with this all started working with VS 2026:

```xml
  <PropertyGroup>
    <WasmBuildNative>true</WasmBuildNative>
  </PropertyGroup>

```
