### ISSUE TITLE
LiveCharts Navigation Exception on iOS and .NET 9

### ISSUE THREAD

**Issue by jai-io** [beto-rodriguez/LiveCharts2#1703]
**Describe the bug**
When navigating away from a page containing a LiveChart graph using the back button, the application throws the following casting exception:
```
System.Exception: Unable to cast to ContentView
   at LiveChartsCore.SkiaSharpView.Maui.ChartBehaviour.<>c__DisplayClass0_0.<On>b__0(Object sender, EventArgs e) in /_/src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/ChartBehaviour.cs:line 58
```

**To Reproduce**
1. Load a page containing a LiveChart graph
2. Navigate away from the page using the back button

**Environment:**
 - OS: Mac OS 15.1 (24B83)
 - iOS Simulator: 18.1
 - .NET SDK: 9.0.100
 - LiveChartsCore.SkiaSharpView.Maui Nuget Package: 2.0.0-rc4.5

**Additional context**
While I haven't thoroughly investigated the Android platform, preliminary observations suggest this issue is also present there.

**Comment by sharifxu** [comment]
i'm experiencing the same issue, any workarounds for this?

**Comment by xhorack** [comment]
The same for me. Exceptionis on all platforms, Win, iOS, Android. On Android there is 'Unable to cast to ContentViewGroup' exception. This happened only after upgrading Microsoft.Maui.Controls to version 9.0.10 from 8 on net9. So i'm not sure if this is addresed to MS or LiveCharts. Also tried latest rc 4.5 of LiveCharts, but behavior is the same. After spending a couple of endless nigths, i have still no workaround.

**Comment by jai-io** [comment]
Looks like this is due to changes in .NET 9 in the way custom control using handlers are cleaned up: [Handler disconnection](https://learn.microsoft.com/en-us/dotnet/maui/whats-new/dotnet-9?view=net-maui-9.0#handler-disconnection).

Adding `HandlerProperties.DisconnectPolicy="Manual"` to the control seems to fix the issue. As an example:
```
                    <maui:CartesianChart
                        Grid.Column="1"
                        HandlerProperties.DisconnectPolicy="Manual"
                        HeightRequest="52"
                        Margin="-16,0,0,0"
                        Series="{Binding Source={RelativeSource AncestorType={x:Type report:StockReportSummaryViewModel}}, Path=StockSummaryPrices.Series}"
                        XAxes="{Binding Source={RelativeSource AncestorType={x:Type report:StockReportSummaryViewModel}}, Path=StockSummaryPrices.XAxes}"
                        YAxes="{Binding Source={RelativeSource AncestorType={x:Type report:StockReportSummaryViewModel}}, Path=StockSummaryPrices.YAxes}"
                        TooltipPosition="Hidden" />
```

**Comment by xhorack** [comment]
Well, you are right, i can confirm on all plaforms everything works fine. Thank you.

**Comment by jo-ruch** [comment]
This happens on Maui 8 on Windows as well when calling `Graph.Handler?.DisconnectHandler()`.

Maui 8.0.21
net8.0-windows10.0.19041.0
LiveChartsCore.SkiaSharpView.Maui 2.0.0-rc4.5

```
274|2024-12-09T13:27:35.3479033+00:00|ERROR|1|VesselHomePage|Threw --> System.Exception: Unable to cast to ContentPanel
   at LiveChartsCore.SkiaSharpView.Maui.ChartBehaviour.<>c__DisplayClass0_0.<On>b__0(Object sender, EventArgs e) in /_/src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/ChartBehaviour.cs:line 74
   at Microsoft.Maui.Controls.Element.OnHandlerChangedCore()
   at Microsoft.Maui.Controls.VisualElement.OnHandlerChangedCore()
   at Microsoft.Maui.Controls.View.OnHandlerChangedCore()
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Handlers.ElementHandler.DisconnectHandler(Object platformView)
   at Microsoft.Maui.Handlers.ElementHandler.Microsoft.Maui.IElementHandler.DisconnectHandler()
   at Slick.Views.Components.TelemetryGraph.OnDestroy()
```

**Comment by maonaoda** [comment]
This might be a problem with the implementation of LiveCharts.
Currently, if HandlerProperties.DisconnectPolicy="Manual" is not added, Maui will automatically Disconnect.
At this time, the HandlerChanged event set in ChartBehaviour will be triggered.
At this time, element.Handler?.PlatformView is already null

```
            var contentView = (Microsoft.Maui.Platform.ContentView?)element.Handler?.PlatformView
                ?? throw new System.Exception("Unable to cast to ContentView");
```

**Comment by maonaoda** [comment]
The correct approach should be to use Handler （ConnectHandler/DisconnectHandler）
instead of HandlerChanged

**Comment by beto-rodriguez** [comment]
I tested and I was able to reproduce with the master branch (v rc-4.5)

The good news is that this was fixed with #1704, @albyrock87, now the chart uses the [ChartViewHandler](https://github.com/beto-rodriguez/LiveCharts2/blob/dev/src/skiasharp/LiveChartsCore.SkiaSharpView.Maui/ChartViewHandler.cs) to connect and disconnect handlers.

I think this could also fix #1725

**Comment by beto-rodriguez** [comment]
This is now working on 2.0.0-rc5.1, thanks for the report!
