### ISSUE TITLE
app crashes with latest SkiaSharp version 

### ISSUE THREAD

**Issue by Th3L0x** [beto-rodriguez/LiveCharts2#1722]
**Describe the bug**
The app crashes with error:

Could not load type of field 'LiveChartsCore.SkiaSharpView.Painting.ImageFilters.DropShadow:_cropRect' (6) due to: Could not resolve type with token 010000cf from typeref (expected class 'CropRect' in assembly '') assembly: type:CropRect member:(null)

with this livechart version:
`<PackageReference Include="LiveChartsCore.SkiaSharpView.Maui" Version="2.0.0-beta.710" />`
 
update these packages to:

```
<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="3.116.0" />
<PackageReference Include="SkiaSharp.Views.Maui.Core" Version="3.116.0" />

```
the error occures

revert these packages back to:
```
<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="2.88.9" />
<PackageReference Include="SkiaSharp.Views.Maui.Core" Version="2.88.9" />
```

its working again

**To Reproduce**
Place a polarchart in page, even an empty one like:
` <lvc:PolarChart HeightRequest="100" WidthRequest="100" />`

**Expected behavior**
Shows the polarchart without crash

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: 
 - OS: Android

**Comment by cloudhal** [comment]
Yes it does, what's the plan for supporting 3.x version of Skiasharp?

**Comment by beto-rodriguez** [comment]
The latest version of LiveCharts is compatible with SkiaSharp 3, it's impossible to make `2.0.0-beta.710` work, SkiaSharp 3 did not even existed when that version was released.

**Comment by cloudhal** [comment]
Thanks @beto-rodriguez , but if you install LiveChartsCore.SkiasharpView.Blazor, it installs SkiaSharp 2.8.8.9-preview.2.2 as a transitive package, upgrading to the latest 3.x versions of SkiSharp breaks it.

**Comment by Th3L0x** [comment]
Same with LiveChartsCore.SkiaSharpView.Maui.

So which version and package should I use in MAUI if I want to update these:
```
<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="2.88.9" />
<PackageReference Include="SkiaSharp.Views.Maui.Core" Version="2.88.9" />
```
to these:
```
<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="3.116.0" />
<PackageReference Include="SkiaSharp.Views.Maui.Core" Version="3.116.0" />
```

Because if I use this package
`<PackageReference Include="LiveChartsCore.SkiaSharpView.Maui" Version="2.0.0-beta.710" />`
with these:
```
<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="3.116.0" />
<PackageReference Include="SkiaSharp.Views.Maui.Core" Version="3.116.0" />
```
then I get this error:
Could not load type of field 'LiveChartsCore.SkiaSharpView.Painting.ImageFilters.DropShadow:_cropRect' (6) due to: Could not resolve type with token 010000cf from typeref (expected class 'CropRect' in assembly '') assembly: type:CropRect member:(null)

**Comment by beto-rodriguez** [comment]
@cloudhal For Blazor plase wait for `rc-5` it should be available in a couple of days at NuGet

@Th3L0x try `rc-4.5`

**Comment by Th3L0x** [comment]
Thank you rc-4.5 solved my issue!

**Comment by beto-rodriguez** [comment]
This is now supported on the latest version of the library, thanks for the report.

**Comment by cloudhal** [comment]
Unfortunately it doesn't render now after upgrade:
System.NullReferenceException: Object reference not set to an instance of an object.
   at SkiaSharp.Views.Blazor.SKGLView.Dispose()

**Comment by Th3L0x** [comment]
I taked a closer look throughout. on 2.0.0-rc4.5

If I navigate from a page (with await Shell.Current.GoToAsync("..", animate: true)) that contains any chart I get this exception:

**System.Exception:** 'Unable to cast to ContentViewGroup'

[MIUIScout App] Enter APP_SCOUT_WARNING State
[MIUIScout App]  (Current message: duration=2503ms seq=3776 late=12ms h=android.os.Handler c=mono.java.lang.RunnableImplementor)
[AppScoutStateMachine] dump trace dirName = 2025-01-16-11-43-27-7936-APP_SCOUT_WARNING-com.Agitur.DeepDate
[MIUIScout App] Event:APP_SCOUT_WARNING Thread:main backtrace:
[MIUIScout App]     at mono.java.lang.RunnableImplementor.n_run(Native Method)
[MIUIScout App]     at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
[MIUIScout App]     at android.os.Handler.handleCallback(Handler.java:958)
[MIUIScout App]     at android.os.Handler.dispatchMessage(Handler.java:99)
[MIUIScout App]     at android.os.Looper.loopOnce(Looper.java:222)
[MIUIScout App]     at android.os.Looper.loop(Looper.java:314)
[MIUIScout App]     at android.app.ActivityThread.main(ActivityThread.java:8680)
[MIUIScout App]     at java.lang.reflect.Method.invoke(Native Method)
[MIUIScout App]     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
[MIUIScout App]     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
[MIUIScout App] Enter APP_SCOUT_HANG state
[MIUIScout App]  (Current message: duration=5005ms seq=3776 late=12ms h=android.os.Handler c=mono.java.lang.RunnableImplementor)
[AppScoutStateMachine] dump trace dirName = 2025-01-16-11-43-30-7936-APP_SCOUT_HANG-com.Agitur.DeepDate
[MIUIScout App] Event:APP_SCOUT_HANG Thread:main backtrace:
[MIUIScout App]     at mono.java.lang.RunnableImplementor.n_run(Native Method)
[MIUIScout App]     at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
[MIUIScout App]     at android.os.Handler.handleCallback(Handler.java:958)
[MIUIScout App]     at android.os.Handler.dispatchMessage(Handler.java:99)
[MIUIScout App]     at android.os.Looper.loopOnce(Looper.java:222)
[MIUIScout App]     at android.os.Looper.loop(Looper.java:314)
[MIUIScout App]     at android.app.ActivityThread.main(ActivityThread.java:8680)
[MIUIScout App]     at java.lang.reflect.Method.invoke(Native Method)
[MIUIScout App]     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
[MIUIScout App]     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
[MIUIScout ANR] get period history msg: (Current message: duration=5801ms seq=3776 late=12ms h=android.os.Handler c=mono.java.lang.RunnableImplementor)
[MIUIScout ANR] get period history msg:messages for the same target android.view.Choreographer$FrameHandler execute time>50ms (count=181 totalwalltime=1052ms h=android.view.Choreographer$FrameHandler

**Comment by t-macintosh** [comment]
> I taked a closer look throughout. on 2.0.0-rc4.5
> 
> If I navigate from a page (with await Shell.Current.GoToAsync("..", animate: true)) that contains any chart I get this exception:
> 
> **System.Exception:** 'Unable to cast to ContentViewGroup'
> 
> [MIUIScout App] Enter APP_SCOUT_WARNING State [MIUIScout App] (Current message: duration=2503ms seq=3776 late=12ms h=android.os.Handler c=mono.java.lang.RunnableImplementor) [AppScoutStateMachine] dump trace dirName = 2025-01-16-11-43-27-7936-APP_SCOUT_WARNING-com.Tets.Test [MIUIScout App] Event:APP_SCOUT_WARNING Thread:main backtrace: [MIUIScout App] at mono.java.lang.RunnableImplementor.n_run(Native Method) [MIUIScout App] at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29) [MIUIScout App] at android.os.Handler.handleCallback(Handler.java:958) [MIUIScout App] at android.os.Handler.dispatchMessage(Handler.java:99) [MIUIScout App] at android.os.Looper.loopOnce(Looper.java:222) [MIUIScout App] at android.os.Looper.loop(Looper.java:314) [MIUIScout App] at android.app.ActivityThread.main(ActivityThread.java:8680) [MIUIScout App] at java.lang.reflect.Method.invoke(Native Method) [MIUIScout App] at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565) [MIUIScout App] at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) [MIUIScout App] Enter APP_SCOUT_HANG state [MIUIScout App] (Current message: duration=5005ms seq=3776 late=12ms h=android.os.Handler c=mono.java.lang.RunnableImplementor) [AppScoutStateMachine] dump trace dirName = 2025-01-16-11-43-30-7936-APP_SCOUT_HANG-com.Test.Test [MIUIScout App] Event:APP_SCOUT_HANG Thread:main backtrace: [MIUIScout App] at mono.java.lang.RunnableImplementor.n_run(Native Method) [MIUIScout App] at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29) [MIUIScout App] at android.os.Handler.handleCallback(Handler.java:958) [MIUIScout App] at android.os.Handler.dispatchMessage(Handler.java:99) [MIUIScout App] at android.os.Looper.loopOnce(Looper.java:222) [MIUIScout App] at android.os.Looper.loop(Looper.java:314) [MIUIScout App] at android.app.ActivityThread.main(ActivityThread.java:8680) [MIUIScout App] at java.lang.reflect.Method.invoke(Native Method) [MIUIScout App] at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565) [MIUIScout App] at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) [MIUIScout ANR] get period history msg: (Current message: duration=5801ms seq=3776 late=12ms h=android.os.Handler c=mono.java.lang.RunnableImplementor) [MIUIScout ANR] get period history msg:messages for the same target android.view.Choreographer$FrameHandler execute time>50ms (count=181 totalwalltime=1052ms h=android.view.Choreographer$FrameHandler

I had the same issue with rc4.5. Installing rc5 works. Installing rc5.1 had a separate exception.

**Comment by beto-rodriguez** [comment]
Closing this — the original report is a NuGet ABI mismatch, not a library bug. `2.0.0-beta.710` was compiled against SkiaSharp 2.88.x, so manually forcing `SkiaSharp.Views.Maui 3.x` produces a typeload error on types like `SKImageFilter.CropRect` that changed between SkiaSharp 2 and 3. Current stable LiveCharts targets SkiaSharp 3 natively — please upgrade and don't pin SkiaSharp directly; let the LiveCharts package bring in the version it was built against.

The other reports in this thread are unrelated to the original title and are over a year old, with many MAUI/Blazor lifecycle fixes shipped since:

- **@cloudhal** — `NRE at SkiaSharp.Views.Blazor.SKGLView.Dispose()` is a separate Blazor lifecycle problem; please open a fresh issue with a minimal Blazor repro on current LiveCharts + your `SkiaSharp.Views.Blazor` version.
- **@Th3L0x / @t-macintosh** — `Unable to cast to ContentViewGroup` on Android after `Shell.Current.GoToAsync("..")` is a MAUI Android handler/navigation issue. Please retest on current stable and, if it still repros, open a fresh issue with the LiveCharts + .NET MAUI versions and a minimal sample.

Keeping bug reports scoped to one symptom each makes them tractable — thanks.
