### ISSUE TITLE
Ran into this crash 

### ISSUE THREAD

**Issue by PhilippElhaus** [beto-rodriguez/LiveCharts2#183]
App ran a couple days already, then this happened. Can sadly not provide anymore info. It killed my entire Application - i have try-catch everywhere - so i suppose it's somehow LiveCharts related. I used pre-release 0.33 2.0.0

Tuesday, September 7, 2021 2:08 PM: Unknown Application Wide Exception: 
Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at LiveChartsCore.Kernel.Data.DataProvider`2.Fetch(ISeries`1 series, IChart chart)+MoveNext()
   at LiveChartsCore.Kernel.Data.DataProvider`2.GetCartesianBounds(CartesianChart`1 chart, IChartSeries`1 series, IAxis`1 x, IAxis`1 y)
   at LiveChartsCore.CartesianSeries`4.GetBounds(CartesianChart`1 chart, IAxis`1 x, IAxis`1 y)
   at LiveChartsCore.LineSeries`9.GetBounds(CartesianChart`1 chart, IAxis`1 secondaryAxis, IAxis`1 primaryAxis)
   at LiveChartsCore.CartesianChart`1.Measure()
   at LiveChartsCore.CartesianChart`1.UpdateThrottlerUnlocked()
   at LiveChartsCore.Kernel.ActionThrottler.Call()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by beto-rodriguez** [comment]
This issue seems also related to #124, I am aware that this happened in previous versions, specially when the update came multiple threads, or when the `tooltip.Show()` method was called while the chart was measured.

This issue is no longer present in the current version, please try to update to the latest version, there are multiple fixes in the latest release (`beta.71`).

**Comment by beto-rodriguez** [comment]
The library has changed a lot since this report, this should not be happening now.

I will close this for now, lt me know if the issue persists.
