### ISSUE TITLE
Unable to remove YAxes

### ISSUE THREAD

**Issue by bbarzeM** [beto-rodriguez/LiveCharts2#312]
**Bug**
I have different line graphs showed with different YAxes.
![image](https://user-images.githubusercontent.com/73690306/144410813-83f5f615-6985-4e96-8915-d7e4ae62c2c6.png)
When I remove all the graph of one Yaxe i would like to remove the Yaxe too. As you can see in here i have one line graph showed and two Y axes
![image](https://user-images.githubusercontent.com/73690306/144411090-41dc3f40-3031-44bf-b456-fa7317dcf223.png)

I tried to fix this thing with the following code but when I remove a Yaxe the library throw an exception. Can you help me?

**To Reproduce**

In the XAML I have

```
<UserControl x:Class="ClientConsumi.UserControlGraph"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" xmlns:lvc="clr-namespace:LiveChartsCore.SkiaSharpView.WPF;assembly=LiveChartsCore.SkiaSharpView.WPF" xmlns:clientconsumi="clr-namespace:ClientConsumi"
             mc:Ignorable="d"
             d:DesignHeight="600" d:DesignWidth="800">
    <UserControl.DataContext>
        <clientconsumi:ViewModel/>
    </UserControl.DataContext>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*" MinHeight="450"/>
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition MinWidth="800" />
        </Grid.ColumnDefinitions>
        <lvc:CartesianChart Grid.Row="0" x:Name="cc" Series="{Binding OSeries}" YAxes="{Binding OYAxes}" XAxes="{Binding OXAxes}" ZoomMode="X" LegendPosition="Top"></lvc:CartesianChart>
    </Grid>
</UserControl>
```

My ViewModel.cs file is this one (sorry if the method comment are in Italian):

```
namespace ClientConsumi
{
    public class YaxesManager
    {
        public String Name;

        public ObservableCollection<String> SignalNameList;

        public YaxesManager(string name, String signalName)
        {
            SignalNameList = new ObservableCollection<string>();
            Name = name;
            SignalNameList.Add(signalName);
        }
    }

    public class ViewModel
    {

        /// <summary>
        /// Collezione con i valori dei segnali da monitorare
        /// </summary>
        public ObservableCollection<LineSeries<DateTimePoint>> OSeries { get; set; }

        /// <summary>
        /// Collezione contenete i valori rappresentati sull'asse X
        /// </summary>
        public ObservableCollection<ICartesianAxis> OXAxes { get; set; }

        /// <summary>
        /// Collezione con i valori delle assi Y (una per ogni unita di misura)
        /// </summary>
        public ObservableCollection<ICartesianAxis> OYAxes { get; set; }

        public ObservableCollection<YaxesManager> OYManger { get; set; }

        private static readonly ILog log = LogManagerWrapper.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public ViewModel()
        {
            #region VALUE

            // using object that implements INotifyPropertyChanged
            // will allow the chart to update everytime a property in a point changes.

            // LiveCharts already provides the ObservableValue class
            // notice you can plot any type, but you must let LiveCharts know how to handle it
            // for more info please see:
            // https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/ViewModelsSamples/General/UserDefinedTypes/ViewModel.cs#L2

            // using a collection that implements INotifyCollectionChanged as your series collection
            // will allow the chart to update every time a series is added, removed, replaced or the whole list was cleared
            // .Net already provides the System.Collections.ObjectModel.ObservableCollection class
            OSeries = new ObservableCollection<LineSeries<DateTimePoint>>();

            #endregion VALUE

            OYAxes = new ObservableCollection<ICartesianAxis>();

            OYManger = new ObservableCollection<YaxesManager>();

            // The UnitWidth is only required for column or financial series
            // because the library needs to know the width of each column, by default the
            // width is 1, but when you are using a different scale, you must let the library know it.
            OXAxes = new ObservableCollection<ICartesianAxis>
            {
                new Axis
                {
                    Labeler = value => new DateTime((long) value).ToString("dd/MM HH:mm"),
                    LabelsRotation = 65,

                    //UnitWidth = TimeSpan.FromMilliseconds(1).Ticks,
                    //MinStep = TimeSpan.FromMilliseconds(1).Ticks,
                    MinStep = 1,

                    // LabelsPaint = null will not draw the axis labels.
                    LabelsPaint = new SolidColorPaint{ Color = SKColors.CornflowerBlue },

                    // SeparatorsPaint = null will not draw the separator lines
                    SeparatorsPaint = new SolidColorPaint { Color = SKColors.LightBlue, StrokeThickness = 3 },
                }
            };

        }

        /// <summary>
        /// In base all'unita di misura restituisce la posizione all'interno della collezione del'asse Y da utilizzare
        /// (nel caso non esista la crea)
        /// </summary>
        /// <param name="measureUnit"></param>
        /// <returns></returns>
        private int GetIndexYAxis(String measureUnit, String signalName)
        {
            if (OYManger.Count(x => x.Name == measureUnit) > 0)
            {
                int pos = OYManger.IndexOf(OYManger.Single(x => x.Name == measureUnit));
                OYManger[pos].SignalNameList.Add(signalName);
                return pos;
            }
            else
            {
                int pos = OYAxes.Count;
                OYAxes.Insert(pos, new Axis() // the "thousands" series will be scaled on this axis
                {
                    Name = measureUnit,
                    ShowSeparatorLines = true,
                    Position = LiveChartsCore.Measure.AxisPosition.End
                });
                OYManger.Insert(pos, new YaxesManager(measureUnit, signalName));
                return pos;
            }
        }

        /// <summary>
        /// Aggiunge un segnale al grafico
        /// </summary>
        /// <param name="oValues">Valori del segnale</param>
        /// <param name="name">Nome del segnale</param>
        /// <param name="measureUnit">Unita di misura del segnale</param>
        /// <returns></returns>
        public int AddSeries(ObservableCollection<DateTimePoint> oValues, String name, String measureUnit)
        {
            try
            {
                // Si controlla se è gia graficato il segnale passato
                if (OSeries.Where(x => x.Name == name).Count() > 0)
                {
                    return (int)UserControlGraph.GRAPH_RES.ALREADY_ADDED;
                }

                // Numero di segnali graficati
                int pos = OSeries.Count;

                // Si possono graficare un numero massimo di segnali
                int limit = 7;
                if (pos == limit)
                {
                    log.Warn($"Too many graph, reached the limit: {limit}");
                    return (int)UserControlGraph.GRAPH_RES.TOO_MUCH_GRAPH;
                }

                int yIndex = GetIndexYAxis(measureUnit, name);

                OSeries.Insert(pos, new LineSeries<DateTimePoint>()
                {
                    Values = oValues,

                    Name = name,

                    // use the line smoothness property to control the curve
                    // it goes from 0 to 1
                    // where 0 is a straight line and 1 the most curved
                    LineSmoothness = 0,
                    //dimension of circle that define points

                    GeometrySize = 10,

                    GeometryFill = new SolidColorPaint(new SKColor(150, 150, 150, 150)),

                    ScalesYAt = yIndex
                });

                return OSeries.Count;
            }
            catch (Exception ex)
            {
                log.Error(ex);
                return (int)UserControlGraph.GRAPH_RES.ERR_ADD_GRAPH;
            }

        }

        /// <summary>
        /// Rimuove un segnale dal grafico e se necessario anche l'asse Y associata
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public int RemoveSeries(String name)
        {
            try
            {
                OSeries.Remove(OSeries.Single(x => x.Name == name));

                int pos = OYManger.IndexOf(OYManger.Single(x => x.SignalNameList.Contains(name)));

                OYManger[pos].SignalNameList.Remove(name);

                if (OYManger[pos].SignalNameList.Count == 0)
                {
                    OYAxes.Remove(OYAxes[pos]);
                    OYManger.RemoveAt(pos);
                }

                return OSeries.Count;
            }
            catch (Exception ex)
            {
                log.Error(ex);
                return (int)UserControlGraph.GRAPH_RES.ERR_DEL_GRAPH;
            }
        }

        /// <summary>
        /// Rimuove tutti i segnali del grafico
        /// </summary>
        public void RemoveAll()
        {
            OSeries.Clear();
            //TODO?
            //YAxes.Clear();
            //YManger.Clear();
            //XAxes.Clear();
        }

    }
}
```

The problem is the instruction  **OYAxes.Remove(OYAxes[pos]);**
I think that the exception is throwed on rendering:

```

System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=LiveChartsCore
  StackTrace:
   at LiveChartsCore.CartesianSeries`4.SoftDeleteOrDispose(IChartView chart)
   at LiveChartsCore.LineSeries`9.SoftDeleteOrDispose(IChartView chart)
   at LiveChartsCore.CartesianChart`1.Measure()
   at LiveChartsCore.Chart`1.<UpdateThrottlerUnlocked>b__139_1()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at LiveChartsCore.SkiaSharpView.WPF.Chart.LiveChartsCore.Kernel.Sketches.IChartView.InvokeOnUIThread(Action action)
   at LiveChartsCore.Chart`1.<UpdateThrottlerUnlocked>b__139_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at LiveChartsCore.Kernel.ActionThrottler.<Call>d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at ClientConsumi.App.Main()
```

 - OS: W10

Thank you for all

**Comment by Foxlider** [comment]
I am having a similar issue when disposing the whole object. 
This issue occurs when having custom Axes on Y (one of multiple) but not when leaving the default Axes.

```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=LiveChartsCore
  StackTrace:
   at LiveChartsCore.CartesianSeries`4.SoftDeleteOrDispose(IChartView chart)
   at LiveChartsCore.LineSeries`9.SoftDeleteOrDispose(IChartView chart)
   at LiveChartsCore.CartesianChart`1.Measure()
   at LiveChartsCore.Chart`1.<UpdateThrottlerUnlocked>b__141_1()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at LiveChartsCore.SkiaSharpView.WPF.Chart.LiveChartsCore.Kernel.Sketches.IChartView.InvokeOnUIThread(Action action)
   at LiveChartsCore.Chart`1.<UpdateThrottlerUnlocked>b__141_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LiveChartsCore.Kernel.ActionThrottler.<Call>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Appli.App.Main(String[] args) in C:\Dev\Appli\App.xaml.cs:line 28
```

**Comment by beto-rodriguez** [comment]
@Foxlider  which object are you disposing?

**Comment by beto-rodriguez** [comment]
Interesting sample @bbarzeM with the current code, the chart always requires at least one axis to work.

But I am seeing your sample and I think it makes sense, I am investigating a way to fix this.

**Comment by beto-rodriguez** [comment]
I think I got it with the referenced commit, it should be fixed in the next release.

**Comment by bbarzeM** [comment]
Thank you 👍 I'll wait it 💯
