### ISSUE TITLE
Usage of Microsoft.UI.Input.Experimental.ExpPointerPoint in LiveChartsCore.SkiaSharpView.WinUI.CartesianChart

### ISSUE THREAD

**Issue by webhaikal** [beto-rodriguez/LiveCharts2#320]
**Describe the bug**
Currently using version 2.0.0-beta.80 and encountering this weird error as what the title says. Pinpointed it to LiveChartsCore.SkiaSharpView.WinUI.CartesianChart class. Not sure how to fix as I couldn't find any reference to it anywhere in the source.

Specifically when debugging, it shows to 3 methods in the class:

```
private void OnPointerReleased(object sender, PointerRoutedEventArgs e)
    {
      ExpPointerPoint currentPoint = e.GetCurrentPoint((UIElement)this);
      _core?.InvokePointerUp(new LvcPoint((float)currentPoint.get_Position().X, (float)currentPoint.get_Position().Y));
      ReleasePointerCapture(e.Pointer);
    }

private void OnPointerPressed(object sender, PointerRoutedEventArgs e)
    {
      CapturePointer(e.Pointer);
      ExpPointerPoint currentPoint = e.GetCurrentPoint((UIElement)this);
      _core?.InvokePointerDown(new LvcPoint((float)currentPoint.get_Position().X, (float)currentPoint.get_Position().Y));
    }

private void OnWheelChanged(object sender, PointerRoutedEventArgs e)
    {
      if (_core == null)
      {
        throw new Exception("core not found");
      }

      CartesianChart<SkiaSharpDrawingContext> cartesianChart = (CartesianChart<SkiaSharpDrawingContext>)_core;
      ExpPointerPoint currentPoint = e.GetCurrentPoint((UIElement)this);
      cartesianChart.Zoom(new LvcPoint((float)currentPoint.get_Position().X, (float)currentPoint.get_Position().Y), (currentPoint.get_Properties().get_MouseWheelDelta() <= 0) ? ZoomDirection.ZoomOut : ZoomDirection.ZoomIn);
    }
```

**Comment by ShortDevelopment** [comment]
## Exception
I'm currently experiencing the same bug using WinUI3 (desktop, unpackaged).
As soon as I hover over the chart, the application crashes with the following exception:
```
System.TypeLoadException: 'Could not load type 'Microsoft.UI.Input.Experimental.ExpPointerPoint' from assembly 'Microsoft.InteractiveExperiences.Projection, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.'
```
### StackTrace (seems to be same as the one above):
```
   at LiveChartsCore.SkiaSharpView.WinUI.CartesianChart.OnPointerMoved(Object sender, PointerRoutedEventArgs e)
   at WinRT._EventSource_global__Microsoft_UI_Xaml_Input_PointerEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, PointerRoutedEventArgs e)
```
## Environment
I'm using .Net 5 with an unpackaged WinUI3 app (using WindowsAppSDK).
### Packages
```xml
<ItemGroup>
	<PackageReference Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />
	<PackageReference Include="LiveChartsCore.SkiaSharpView.WinUI" Version="2.0.0-beta.80" />
	<PackageReference Include="Microsoft.Windows.CsWinRT" Version="1.4.1" />
	<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />
	<PackageReference Include="System.Drawing.Common" Version="6.0.0" />
	<Manifest Include="$(ApplicationManifest)" />
</ItemGroup>
```

**Comment by webhaikal** [comment]
Right now, the way to fix seems to be building the libraries from the repo and reference it

**Comment by beto-rodriguez** [comment]
It is fixed in the current version of the library, the  references were updated to WindowsAppSDK 1.0, the current NuGet package uses a preview version.

**Comment by webhaikal** [comment]
I see, and how do I get the current version?

**Comment by beto-rodriguez** [comment]
It will be published soon

**Comment by webhaikal** [comment]
Alright thanks
