### ISSUE TITLE
Charts not working for multiviews scenario [UWP]

### ISSUE THREAD

**Issue by bexolder2** [beto-rodriguez/LiveCharts2#400]
I try using chart for a few views, but get exception in InitializeComponent();:
`Cannot create instance of type 'LiveCharts.Uwp.Axis'`

Stack trace:

   ```
at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at TestUWP.AppViews.ChartView.InitializeComponent() in d:\TestUWP\obj\x64\Debug\AppViews\ChartView.g.i.cs:line 33
   at TestUWP.AppViews.ChartView..ctor() in d:\TestUWP\TestUWP\AppViews\ChartView.xaml.cs:line 10
```

Sometimes it working for one CoreApplicationView, but newer working with two CoreApplicationView. I don't see a pattern in this behavior. I also try create Axis in code behind, but get same exception. This look like internal Live-Charts exception. 

View:
```
<Page
    x:Class="TestUWP.AppViews.ChartView"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:lvc="using:LiveCharts.Uwp"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <lvc:CartesianChart Series="{Binding ChartPointsOHLC}">
            <lvc:CartesianChart.AxisX>
                <lvc:Axis Labels="{Binding OhlcDates}"/>
            </lvc:CartesianChart.AxisX>
        </lvc:CartesianChart>
    </Grid>
</Page>
```
VIewModel:

```
public class ViewModel : INotifyPropertyChanged 
    {
        private SeriesCollection chartPointsOHLC;
        private ObservableCollection<string> ohlcDates;

        public event PropertyChangedEventHandler PropertyChanged;
        public void OnPropertyChanger(string name)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
        }


        public ObservableCollection<string> OhlcDates
        {
            get => ohlcDates;
            set
            {
                ohlcDates = value;
                OnPropertyChanger("OhlcDates");
            }
        }

        public SeriesCollection ChartPointsOHLC
        {
            get => chartPointsOHLC;
            set
            {
                chartPointsOHLC = value;
                OnPropertyChanger("ChartPointsOHLC");
            }
        }

        public ViewModel()
        {
            OhlcDates = new ObservableCollection<string>();
            ChartPointsOHLC = new SeriesCollection
            {
                new OhlcSeries {
                    Values = new ChartValues<OhlcPoint>()
                }
            };

            Random rnd = new Random();
            for(int i = 0; i < 100; i++)
            {
                ChartPointsOHLC[0].Values.Add(new OhlcPoint(rnd.Next(0, 100), rnd.Next(0, 100), rnd.Next(0, 100), rnd.Next(0, 100)));
                OhlcDates.Add(rnd.Next(0, 100).ToString());
            }
        }
    }
```

Creating new view with chart:

```
private async void Button_Click(object sender, RoutedEventArgs e)
        {
            CoreApplicationView newView = CoreApplication.CreateNewView();
            int newViewId = 0;
            await newView.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, async () =>
            {
                Frame frame = new Frame();
                frame.Navigate(typeof(ChartView));
                Window.Current.Content = frame;
                Window.Current.Activate();
                var view = ApplicationView.GetForCurrentView();
                view.Title = chartNumber.ToString();
                chartNumber++;

                newViewId = view.Id;
                bool viewShown = await ApplicationViewSwitcher.TryShowAsStandaloneAsync(newViewId);
            });
        }
```

1. Declare chart in xaml
2. Binding to viewmodels data 
3. Try create new CoreApplicationView
4. See error Cannot create instance of type 'LiveCharts.Uwp.Axis'

 - OS: Windows 10.0.19042
 - Nuget: LiveCharts.Uwp v. 0.8.0
 - UWP project minimal version: 1809; Build 17763
 - UWP project target version: 1809; Build 17763

**Comment by beto-rodriguez** [comment]
Notice you are using LiveCharts v0.8.0, try to use the new package 

https://www.nuget.org/packages/LiveChartsCore.SkiaSharpView.UWP/2.0.0-beta.101
