### ISSUE TITLE
My app may crash due to LiveChart

### ISSUE THREAD

**Issue by FanIT** [beto-rodriguez/LiveCharts2#513]
Hello. My project using Avalonia and LiveChart. I have a suspiction that crashes in my app because I updated LiveChart beta.80 to beta.300.
If i'm running my app in debug mode from Visual Studio to work fine, but if i'm running publish version, getting crash of the app.
If i roll back to beto.80 then work fine again.
In Windows event log have a event 1026 .NET Runtime.
```
Application: SysMonAvalonia.exe
CoreCLR Version: 6.0.522.21309
.NET Version: 6.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: An item with the same key has already been added. Key: [9, System.Collections.Generic.List`1[Avalonia.VisualTree.IVisual]]
   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T )
   at System.Collections.Generic.SortedDictionary`2.Add(TKey , TValue )
   at Avalonia.Rendering.DirtyVisuals.Add(IVisual visual) in /_/src/Avalonia.Visuals/Rendering/DirtyVisuals.cs:line 61
   at Avalonia.Rendering.DeferredRenderer.AddDirty(IVisual visual) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 126
   at Avalonia.Visual.InvalidateVisual() in /_/src/Avalonia.Visuals/Visual.cs:line 300
   at LiveChartsCore.SkiaSharpView.Avalonia.MotionCanvas.OnCanvasCoreInvalidated(MotionCanvas`1 sender)
   at LiveChartsCore.Motion.MotionCanvas`1.Invalidate()
   at LiveChartsCore.CartesianChart`1.Measure()
   at LiveChartsCore.Chart`1.<UpdateThrottlerUnlocked>b__144_1()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 193
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at SysMonAvalonia.Program.Main(String[] args)
```

My [ChartModel](https://github.com/FanIT/SysMonAvalonia/blob/main/SysMonAvalonia/Models/ChartModel.cs)

**Comment by FanIT** [comment]
I have update the Avalonia to latest version 0.10.15 today, but the issue still occurs.

**Comment by beto-rodriguez** [comment]
This is strange, it seems an Avalonia issue I will take a look at your repo an see if I can find something there.

**Comment by FanIT** [comment]
Thanks. I have update my repo with an last edits.

**Comment by FanIT** [comment]
I'm have catched exception unhandled in VS.
![VSscreen](https://user-images.githubusercontent.com/20283004/172349091-d2d3ffef-238a-4950-aa1f-f6f43208bce7.PNG)

**Comment by FanIT** [comment]
I checked several versions of LiveChart. Latest working version beta.101 for me.

**Comment by beto-rodriguez** [comment]
That helps a lot thanks, I actually changed the Avalonia renderer some versions ago, I will that up.

**Comment by FanIT** [comment]
@agillet76, hi. 
No yet. I'm using beta.101 now. The version is working a fine for my app.

**Comment by agillet76** [comment]
We observe the same issue with LiveChart and Avalonia. 
I tried our test application running under Visual Studio in debug mode  with livechart 2.0.0-beta.101, 2.0.0-beta.300 and Avalonia 0.10.15 , 0.10.16 .
The crash is sporadic it can be seconds or hours.
We are updating our chart at 20 Hz  , we use our charts to display temperature/pressure sensor data from our devices in real time.
I have posted our test application here: 
https://github.com/agillet76/livechart-avalonia-crash


Exception thrown: 'System.ArgumentException' in System.Collections.dll
[Visual] Exception in render loop: 'System.ArgumentException: An item with the same key has already been added. Key: [41, System.Collections.Generic.List`1[Avalonia.VisualTree.IVisual]]
   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
   at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)
   at Avalonia.Rendering.DirtyVisuals.Add(IVisual visual) in /_/src/Avalonia.Visuals/Rendering/DirtyVisuals.cs:line 56
   at LiveChartsCore.SkiaSharpView.Avalonia.MotionCanvas.CustomDrawOp.Render(IDrawingContextImpl context)
   at Avalonia.Rendering.SceneGraph.CustomDrawOperation.Render(IDrawingContextImpl context) in /_/src/Avalonia.Visuals/Rendering/SceneGraph/CustomDrawOperation.cs:line 30
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 437
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.Render(IDrawingContextImpl context, VisualNode node, IVisual layer, Rect clipBounds) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 446
   at Avalonia.Rendering.DeferredRenderer.RenderToLayers(Scene scene) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 492
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 378
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 323
   at Avalonia.Rendering.DeferredRenderer.Avalonia.Rendering.IRenderLoopTask.Render() in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 275
   at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time) in /_/src/Avalonia.Visuals/Rendering/RenderLoop.cs:line 147' (RenderLoop #33163964)

**Comment by beto-rodriguez** [comment]
I tested the latest Avalonia preview, and it seems that this issue is gone there.

This branch is ready to work with the latest Avalonia preview package.

https://github.com/beto-rodriguez/LiveCharts2/issues/593

**Comment by FanIT** [comment]
Hi, Beto. Sorry that I didn't reply for a while. I'm testing beta.502 with latest Avalonia 11 preview and i don't watching crashes my a app anymore.
Thanks you. Good job.
Should i close the issual?

**Comment by beto-rodriguez** [comment]
Thanks for the feedback!

> Thanks, you. Good job.

Not only my job 😄, but the Avalonia team also improved that, and made it easier for me, maybe we should keep this open until the Avalonia Ga version is released.

**Comment by hahagu** [comment]
A similar issue seems to exist still on the preview version.
It happens while moving the chart points via mouse in zoom.

<details>
<summary>Callstack</summary>

```
 	System.Private.CoreLib.dll!System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()	Unknown
 	System.Private.CoreLib.dll!System.Collections.Generic.List<System.__Canon>.Enumerator.MoveNext()	Unknown
 	LiveChartsCore.dll!LiveChartsCore.Kernel.Providers.DataFactory<LiveChartsCore.Defaults.ObservableValue, LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext>.EnumerateChartEntities(LiveChartsCore.ISeries<LiveChartsCore.Defaults.ObservableValue> series, LiveChartsCore.Kernel.Sketches.IChart chart)	Unknown
 	LiveChartsCore.dll!LiveChartsCore.Kernel.Providers.DataFactory<LiveChartsCore.Defaults.ObservableValue, LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext>.Fetch(LiveChartsCore.ISeries<LiveChartsCore.Defaults.ObservableValue> series, LiveChartsCore.Kernel.Sketches.IChart chart)	Unknown
 	System.Linq.dll!System.Linq.Enumerable.WhereSelectEnumerableIterator<LiveChartsCore.Kernel.ChartPoint, <>f__AnonymousType0<double, LiveChartsCore.Kernel.ChartPoint>>.ToArray()	Unknown
 	System.Linq.dll!System.Linq.Buffer<<>f__AnonymousType0<double, LiveChartsCore.Kernel.ChartPoint>>.Buffer(System.Collections.Generic.IEnumerable<<>f__AnonymousType0<double, LiveChartsCore.Kernel.ChartPoint>> source)	Unknown
 	System.Linq.dll!System.Linq.OrderedEnumerable<<>f__AnonymousType0<double, LiveChartsCore.Kernel.ChartPoint>>.GetEnumerator()	Unknown
 	LiveChartsCore.dll!LiveChartsCore.Kernel.Extensions.SelectFirst<<>f__AnonymousType0<double, LiveChartsCore.Kernel.ChartPoint>, LiveChartsCore.Kernel.ChartPoint>(System.Collections.Generic.IEnumerable<<>f__AnonymousType0<double, LiveChartsCore.Kernel.ChartPoint>> source, System.Func<<>f__AnonymousType0<double, LiveChartsCore.Kernel.ChartPoint>, LiveChartsCore.Kernel.ChartPoint> predicate)	Unknown
 	System.Linq.dll!System.Collections.Generic.LargeArrayBuilder<LiveChartsCore.Kernel.ChartPoint>.AddRange(System.Collections.Generic.IEnumerable<LiveChartsCore.Kernel.ChartPoint> items)	Unknown
 	System.Linq.dll!System.Collections.Generic.SparseArrayBuilder<LiveChartsCore.Kernel.ChartPoint>.ReserveOrAdd(System.Collections.Generic.IEnumerable<LiveChartsCore.Kernel.ChartPoint> items)	Unknown
 	System.Linq.dll!System.Linq.Enumerable.SelectManySingleSelectorIterator<LiveChartsCore.Kernel.Sketches.IChartSeries<LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext>, LiveChartsCore.Kernel.ChartPoint>.ToArray()	Unknown
 	System.Linq.dll!System.Linq.Enumerable.ToArray<LiveChartsCore.Kernel.ChartPoint>(System.Collections.Generic.IEnumerable<LiveChartsCore.Kernel.ChartPoint> source)	Unknown
 	LiveChartsCore.dll!LiveChartsCore.Chart<LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext>.TooltipThrottlerUnlocked.AnonymousMethod__152_1()	Unknown
>	Avalonia.Base.dll!Avalonia.Threading.JobRunner.RunJobs(Avalonia.Threading.DispatcherPriority? priority) Line 38	C#
 	Avalonia.Win32.dll!Avalonia.Win32.Win32Platform.WndProc(System.IntPtr hWnd, uint msg, System.IntPtr wParam, System.IntPtr lParam) Line 270	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Avalonia.Win32.dll!Avalonia.Win32.Win32Platform.RunLoop(System.Threading.CancellationToken cancellationToken) Line 210	C#
 	Avalonia.Base.dll!Avalonia.Threading.Dispatcher.MainLoop(System.Threading.CancellationToken cancellationToken) Line 62	C#
 	Avalonia.Controls.dll!Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(string[] args) Line 121	C#
 	SampleProgram.dll!SampleProgram.Program.Main(string[] args) Line 14	C#
```

</details>

![Untitled](https://user-images.githubusercontent.com/3746349/198404634-2041e2ba-a736-4282-9069-d0268042fd27.png)

**Comment by hahagu** [comment]
> A similar issue seems to exist still on the preview version. It happens while moving the chart points via mouse in zoom.
> Callstack
> 
> ![Untitled](https://user-images.githubusercontent.com/3746349/198404634-2041e2ba-a736-4282-9069-d0268042fd27.png)

To be exact, I think this happens while a point is updated out of the collection, and I try to go left from the curve.

**Comment by beto-rodriguez** [comment]
@hahagu probably a threading issue and maybe different to this report. I am seriously thinking on change the way tooltips work in the library, maybe you should try https://github.com/beto-rodriguez/LiveCharts2/issues/225#issuecomment-1012488255.

I will close this for now, since it seems that it is fixed win the latest version of Avalonia.
