### ISSUE TITLE
StackedColumnSeries crash

### ISSUE THREAD

**Issue by ClubberLangG** [beto-rodriguez/LiveCharts2#63]
**Describe the bug**
I have a crash when I replace my ColumnSeries with StackedColumnSeries.
I have an ArgumentOutOfRangeException... 

   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at LiveChartsCore.Kernel.Stacker`1.StackPoint(ChartPoint point, Int32 seriesStackPosition)
   at LiveChartsCore.Kernel.Data.DataProvider`2.GetCartesianBounds(CartesianChart`1 chart, IChartSeries`1 series, IAxis`1 x, IAxis`1 y)
   at LiveChartsCore.CartesianSeries`4.GetBounds(CartesianChart`1 chart, IAxis`1 x, IAxis`1 y)
   at LiveChartsCore.StackedColumnSeries`4.GetBounds(CartesianChart`1 chart, IAxis`1 secondaryAxis, IAxis`1 primaryAxis)
   at LiveChartsCore.CartesianChart`1.Measure()
   at LiveChartsCore.CartesianChart`1.UpdateThrottlerUnlocked()
   at LiveChartsCore.Kernel.ActionThrottler.<Call>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)

Here is what I have now
![image](https://user-images.githubusercontent.com/67060390/123460602-2a13c600-d5e8-11eb-8ace-0488a5e8b06c.png)

And what I'm looking for : 

![image](https://user-images.githubusercontent.com/67060390/123460825-8a0a6c80-d5e8-11eb-8337-53692a80b0d7.png)

For now, each bar override the other one, I want all the values at the same date, appear as stacked bar.

**Comment by anthony-glenwright** [comment]
I found that when adding StackedRowSeries or StackedColumnSeries objects to the series, I had to make sure that the values list for each of them have the same number of elements, otherwise you get the ArgumentOutOfRangeException.  If you need to include empty values, you can use double.NaN.

**Comment by LabuzzMichal** [comment]
@beto-rodriguez It happens when Series in StackedSeries doesnt have the same length. Are you aware of any workaround? StackedColumnSeries  with DateTimePoint also seems to crash the chart

**Comment by beto-rodriguez** [comment]
This seems to be a valid limitation, I mean we need them to have the same length on every series so we can stack the points using the index (the position f every point) to do the stack, otherwise it would have no sense as far as I can see, as a workaround as @anthony-glenwright says you could use `double.Nan` or even `0` would work (I think).

Yes @LabuzzMichal there is an issue when using date time, probably related with the loss of precision when doing the stack, I'm checking that.

**Comment by beto-rodriguez** [comment]
The date time issue is fixed with the referenced commit.

Also now we will get a better error message when if any of the `Series.Values` properties have  different length.

https://github.com/beto-rodriguez/LiveCharts2/commit/7a0bd4e099150420fee44d778db354c66d33d3c1#diff-91582a5e26ad582071e0b9da4041fcc02d3b6f926690c96a9071283fd92cccfeR96

This fill will be included in the next release of the library
