### ISSUE TITLE
Setting UpdaterThrottler throws XamlParseException

### ISSUE THREAD

**Issue by k-wozniak** [beto-rodriguez/LiveCharts2#699]
Hi, I am trying to change the diagram's update rate.
When trying to set UpdaterThrottler: 

`<lvc:CartesianChart UpdaterThrottler="00:00:00.500" Series="{Binding Series}" XAxes="{Binding XAxes}" YAxes="{Binding YAxes}"/>`

When running the program during the View initialization I get the following exception:

> System.Windows.Markup.XamlParseException: ''Set property 'LiveChartsCore.SkiaSharpView.WPF.Chart.UpdaterThrottler' threw an exception.'
> Inner Exception: Exception: core not set yet.

Do you know how I could set the core?

**To Reproduce**
Add _UpdaterThrottler="00:00:00.500"_ to a CartesianChart.
Example project that crashes: https://github.com/k-wozniak/UpdaterThrottlerCrasher

**Expected behavior**
I've expected to just change update speed from the default 10ms.

**Desktop:**
 - OS: Windows, WPF C#
 - LiveChartsCore.SkiaSharpView.WPF
 - Version 2.0.0-beta.511

_(Also, awesome library, works and looks great!)_

**Comment by k-wozniak** [comment]
Hi, I've created a minimal WPF C# example project, where setting UpdaterThrottler causes the runtime error.
Project: https://github.com/k-wozniak/UpdaterThrottlerCrasher

**Comment by pablo-remy** [comment]
I ran into this same issue, although in my case I'm developing on WinUI 3 + C# for Windows 10 Pro 64bit. I tried to work around it by setting up the UpdaterThrottler programmatically instead of in XAML but it throws 

> System.Exception: 'core not set yet.' 

I did this by calling the following. Note that "MyCartesianChart" is the name of my lvc:CartesianChart in XAML
 
 `MyCartesianChart.UpdaterThrottler = TimeSpan.FromMilliseconds(500); `

Details of the exception below

```
System.Exception
  HResult=0x80131500
  Message=core not set yet.
  Source=LiveChartsCore.SkiaSharpView.WinUI
  StackTrace:
   at LiveChartsCore.SkiaSharpView.WinUI.CartesianChart.set_UpdaterThrottler(TimeSpan value)
   at Test_App_2.Views.CalorimetricTestPage..ctor() in C:\Users\pablo\source\repos\oven-calibration-app\Test App 2\Test App 2\Views\CalorimetricTestPage.xaml.cs:line 44
   at Test_App_2.Test_App_2_XamlTypeInfo.XamlTypeInfoProvider.Activate_89_CalorimetricTestPage() in C:\Users\pablo\source\repos\oven-calibration-app\Test App 2\Test App 2\obj\x64\Debug\net6.0-windows10.0.19041.0\XamlTypeInfo.g.cs:line 480
   at Test_App_2.Test_App_2_XamlTypeInfo.XamlUserType.ActivateInstance() in C:\Users\pablo\source\repos\oven-calibration-app\Test App 2\Test App 2\obj\x64\Debug\net6.0-windows10.0.19041.0\XamlTypeInfo.g.cs:line 4588
   at ABI.Microsoft.UI.Xaml.Markup.IXamlType.Do_Abi_ActivateInstance_13(IntPtr thisPtr, IntPtr* result)
```

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is fixed with the referenced commit and will be included in the next version of the library,
