### ISSUE TITLE
Only Android environment has an error. Maui

### ISSUE THREAD

**Issue by hukjin** [beto-rodriguez/LiveCharts2#864]
if I use the add font and then use the paint function.

but ALL IOS working fine but only Android environment has a like the error.
**example)**        
       ` Chart.LegendTextPaint = new SolidColorPaint()
        {
            Color = new SKColor(0, 0, 0),
            SKTypeface = SKTypeface.FromFamilyName("AppleGothic"),
        };`

`Chart.TooltipTextPaint = new SolidColorPaint() {
            Color = new SKColor(0, 0, 0),
            SKTypeface = SKTypeface.FromFamilyName("AppleGothic"), 
};`

`XAxis = new Axis[] { new Axis{ Labels = new[] { "" },  TextSize = 30, LabelsPaint = new SolidColorPaint{
                    Color = SKColors.Black,
                    FontFamily = "AppleGothic"
                },
            }
};`

**Error Message)**

System.NullReferenceException: Object reference not set to an instance of an object.
  at at LiveChartsCore.SkiaSharpView.Painting.SolidColorPaint.Dispose()
  at at LiveChartsCore.Motion.MotionCanvas`1[[LiveChartsCore.SkiaSharpView.Drawing.SkiaSharpDrawingContext, LiveChartsCore.SkiaSharpView, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc92a3e13d40c573]].DrawFrame(SkiaSharpDrawingContext context)
  at at LiveChartsCore.SkiaSharpView.Maui.MotionCanvas.OnCanvasViewPaintSurface(Object sender, SKPaintSurfaceEventArgs args)
  at SkiaSharp.Views.Maui.Controls.SKCanvasView.OnPaintSurface(SKPaintSurfaceEventArgs e) in D:\a\1\s\source\SkiaSharp.Views.Forms\SkiaSharp.Views.Forms.Shared\SKCanvasView.cs:74
  at SkiaSharp.Views.Maui.Controls.SKCanvasView.SkiaSharp.Views.Maui.ISKCanvasView.OnPaintSurface(SKPaintSurfaceEventArgs e) in D:\a\1\s\source\SkiaSharp.Views.Maui\SkiaSharp.Views.Maui.Controls\SKCanvasView.HandlerImpl.cs:33
  at SkiaSharp.Views.Maui.Handlers.SKCanvasViewHandler.OnPaintSurface(Object sender, SKPaintSurfaceEventArgs e) in D:\a\1\s\source\SkiaSharp.Views.Maui\SkiaSharp.Views.Maui.Core\Handlers\SKCanvasView\SKCanvasViewHandler.Android.cs:68
  at SkiaSharp.Views.Android.SKCanvasView.OnPaintSurface(SKPaintSurfaceEventArgs e) in D:\a\1\s\source\SkiaSharp.Views\SkiaSharp.Views.Android\SKCanvasView.cs:134
  at SkiaSharp.Views.Android.SKCanvasView.OnDraw(Canvas canvas) in D:\a\1\s\source\SkiaSharp.Views\SkiaSharp.Views.Android\SKCanvasView.cs:113
  at Android.Views.View.n_OnDraw_Landroid_graphics_Canvas_(IntPtr jnienv, IntPtr native__this, IntPtr native_canvas) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.View.cs:18341
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:121

**Comment by beto-rodriguez** [comment]
Thanks for the report, after checking this out, it makes sense that the font "AppleGothic" does not exists on Android, you must load font from a file, or use a font that is available on both platforms.
