### ISSUE TITLE
Library not working on Linux out of the box

### ISSUE THREAD

**Issue by enricobenedos** [beto-rodriguez/LiveCharts2#873]
**Describe the bug**
After some positive testing on my macOS environment I deployed my app that use `LiveChartsCore.SkiaSharpView` library to Ubuntu 20.04 LTS production VPS and the same code stop working.

**To Reproduce**
1. Include `LiveChartsCore.SkiaSharpView` in an ASP.NET Web API project
2. Execute this code in a controller endpoint:
```c#
var series = new ISeries[]
            {
                new LineSeries<double>
                {
                    Values = myData,
                    LineSmoothness = 1,
                    GeometrySize = 0,
                    Stroke = new SolidColorPaint
                    {
                        Color = SKColors.Teal,
                        StrokeCap = SKStrokeCap.Round,
                        StrokeThickness = 2,
                        //PathEffect = new DashEffect(new float[] { 5, 5 })
                    },
                    //Fill = new SolidColorPaint
                    //{
                    //    Color = SKColors.Teal.WithAlpha(50),
                    //    //PathEffect = new DashEffect(new float[] { 5, 5 })
                    //},
                },
            };

            SKCartesianChart sKCartesianChart = new SKCartesianChart()
            {
                Series = series,
                XAxes = new Axis[]
                {
                    new Axis
                    {
                        Labeler=l=>$"{Math.Truncate(l)} km"
                    }
                },
                YAxes = new Axis[]
                {
                    new Axis
                    {
                        Labeler=l=>$"{Math.Truncate(l)} m"
                    }
                },
                Height = 400,
                Width = 600
            };

            string imgName = Guid.NewGuid().ToString() + ".png";

            sKCartesianChart.SaveImage(imgName, quality: 100);
```
4. This error is generated
```console
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/libSkiaSharp.so: cannot open shared object file: No such file or directory
/var/www/wamii-api-dev/libSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/var/www/wamii-api-dev/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/libSkiaSharp: cannot open shared object file: No such file or directory
/var/www/wamii-api-dev/libSkiaSharp: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/liblibSkiaSharp: cannot open shared object file: No such file or directory
/var/www/wamii-api-dev/liblibSkiaSharp: cannot open shared object file: No such file or directory

   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKImageInfo..ctor(Int32 width, Int32 height)
   at LiveChartsCore.SkiaSharpView.SKCharts.InMemorySkiaSharpChart.GetImage()
   at LiveChartsCore.SkiaSharpView.SKCharts.InMemorySkiaSharpChart.SaveImage(String path, SKEncodedImageFormat format, Int32 quality)
   at WamiiCore.Api.Services.GpxService.GetGpxAltimetryChart(TourDto tourDto) in /home/vsts/work/1/s/WamiiCore.Api/Services/GpxService.cs:line 125
   at WamiiCore.Api.Controllers.GPXController.GetGPXAltimetryChart(Int32 tourId) in /home/vsts/work/1/s/WamiiCore.Api/Controllers/GPXController.cs:line 80
   at lambda_method163(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at WamiiCore.Api.Utilities.AuthenticationMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/WamiiCore.Api/Utilities/AuthenticationMiddleware.cs:line 57
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
6. See error

**Expected behavior**
I simply expect that this library working with .NET 7 is fully compatible with all the environment supported, included linux.

**Comment by tbrillet** [comment]
The issue is usually related to skiasharp that needs to have the libfontconfig1 package installed on linux.
