### ISSUE TITLE
Incompatible with avalonia preview 6

### ISSUE THREAD

**Issue by hahagu** [beto-rodriguez/LiveCharts2#972]
**Describe the bug**
LiveCharts2 will crash when used with avalonia preview 6

**To Reproduce**
1. Use avalonia preview 6 with LiveCharts2
2. Observe crash

**Expected behavior**
Working as intended

**Additional context**
Stacktrace:

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart' threw an exception.
  Source=LiveChartsCore.SkiaSharpView.Avalonia
  StackTrace:
   at LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart.!XamlIlPopulateTrampoline(CartesianChart )
   at LiveChartsCore.SkiaSharpView.Avalonia.CartesianChart..ctor()
   at GUI.Views.Controls.Cards.MonitorCard.!XamlIlPopulate(IServiceProvider , MonitorCard ) in C:\Users\Mingu\Documents\Projects\SW\GUI\Views/Controls/Cards/MonitorCard.axaml:line 35
   at GUI.Views.Controls.Cards.MonitorCard.!XamlIlPopulateTrampoline(MonitorCard )
   at GUI.Views.Controls.Cards.MonitorCard.InitializeComponent(Boolean loadXaml) in C:\Users\Mingu\Documents\Projects\SW\GUI\Avalonia.Generators\Avalonia.Generators.NameGenerator.AvaloniaNameSourceGenerator\GUI.Views.Controls.Cards.MonitorCard.g.cs:line 25
   at GUI.Views.Controls.Cards.MonitorCard..ctor(ISensor bindingSensor) in C:\Users\Mingu\Documents\Projects\SW\GUI\Views\Controls\Cards\MonitorCard.axaml.cs:line 88
   at GUI.Views.Pages.MonitorPage.AddCards(IList sensorIds) in C:\Users\Mingu\Documents\Projects\SW\GUI\Views\Pages\MonitorPage.axaml.cs:line 47
   at GUI.Views.Pages.MonitorPage.<>c__DisplayClass3_0.<SensorMonitorsOnCollectionChanged>b__0() in C:\Users\Mingu\Documents\Projects\SW\GUI\Views\Pages\MonitorPage.axaml.cs:line 63
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at GUI.Program.Main(String[] args) in C:\Users\Mingu\Documents\Projects\SW\GUI\Program.cs:line 26

  This exception was originally thrown at this call stack:

Inner Exception 1:
MissingMethodException: Method not found: 'Avalonia.StyledProperty`1<!!1> Avalonia.AvaloniaProperty.Register(System.String, !!1, Boolean, Avalonia.Data.BindingMode, System.Func`2<!!1,Boolean>, System.Func`3<Avalonia.AvaloniaObject,!!1,!!1>, System.Action`2<Avalonia.AvaloniaObject,Boolean>)'.
```

**Comment by qfmee** [comment]
I have also encountered such a problem. Have you solved it now?

**Comment by Mrxx99** [comment]
I think that is only solvable by upgrading the library to target previe 6 of Avalonia 11, there is a PR here: https://github.com/beto-rodriguez/LiveCharts2/pull/978
